### CREATE JABATAN MAHASISWA
PUT http://localhost:8080/users/6/password
content-type: application/json

{
    "id": 6,
    "oldPassword":"12345",
    "newPassword":"1234"
    
}
###

POST http://localhost:8080/users/signin
content-type: application/json

{
    "email": "admin1@mail.com",
    "password": "123"
}
###

POST http://localhost:8080/users/signup
content-type: application/json

{
    "name": "Universitas gua",
    "email": "kokosa@mail.com",
    "password": "123456",
    "namaRektor":"joko",
    "ktpRektor":"koko.png",
    "alamat":"jakarta"
}