### GET likes (fitur sementara)
GET http://localhost:8080/like
### GET Saves (fitur sementara)
GET http://localhost:8080/save
### GET POSTS
GET http://localhost:8080/posts?page=1&limit=30&idUser=3
### GET POSTS (idPost)
GET http://localhost:8080/posts?page=1&limit=30&idUser=3&idPost=2


### GET POSTS (saved)
GET http://localhost:8080/posts?page=1&limit=10&idUser=1&isSave=true

### GET POSTS (idUserUniversitas) => get post di univ
GET http://localhost:8080/posts?page=1&limit=10&idUser=3&idUserUniversitas=3

### GET POSTS (isNews)  => get all post dengan status isNews true
GET http://localhost:8080/posts?page=1&limit=30&idUser=1&isNews=true

### GET POST => get single post
GET http://localhost:8080/posts/2

### CREATE POST BIASA
POST http://localhost:8080/posts
content-type: application/json

{
    "idUser": 1,
    "materi": "https://source.unsplash.com/random/500x500",
    "caption": "lorem ipsum dolor is amet lorem ipsum amet is dolor asf adfasdfasdf ",
    "isNews": true,
    "idUserUniversitas":1
}

### CREATE POST NEWS
POST http://localhost:8080/posts
content-type: application/json

{
    "idUser": 3,
    "materi": "dummypost3.jpg",
    "caption": "Lorem ipsum dolor is amet awaw",
    "isNews": true,
    "idUserUniversitas":5
}
### SAVE POST
POST http://localhost:8080/posts/1/save
content-type: application/json

{
    "idUser": 1 ,
    "idPost": 1 
}
### UNSAVE POST
POST http://localhost:8080/posts/1/unsave
content-type: application/json

{
    "idUser": 1 ,
    "idPost": 1 
}

### LIKE POST
POST http://localhost:8080/posts/6/like
content-type: application/json

{
    "idUser": 3 ,
    "idPost": 6 
}
### UNLIKE POST
POST http://localhost:8080/posts/3/unlike
content-type: application/json

{
    "idUser": 3 ,
    "idPost": 3
}
 
### DELETE POST
DELETE http://localhost:8080/posts/1

### DELETE POSTS => delete semua post (fitur sementara)
DELETE http://localhost:8080/posts
